# Generated by Django 4.0.1 on 2022-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacore', '0002_compromisso_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
