# Generated by Django 4.0.1 on 2022-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendacore', '0003_compromisso_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='situacao',
            field=models.CharField(default='Aberto', max_length=10),
        ),
    ]
